# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5cb482552131eaab6a208113aca135762ba97dd2ee6f98537b70edcb110a96098ba4490cfb50e884974f73b3ca934d218890249b98cf7a78bd4e0383a92e489

test:
  secret_key_base: 55449f50efcf8813845128ae00ed16ed9290ae0c7e3e51f827f9bfba71154c09487150411d66a3903ae438e4f8283d4862f286c0e9ecc9da500098dc780d890b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
